import { useGLTF } from '@react-three/drei'

/*
R3F code Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export default function Model(props) {
  const { scene } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/paint-brush/model.gltf',
  )
  return <primitive object={scene} {...props} />
}
